# Generated by Django 4.2.5 on 2023-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('desc', models.TextField(max_length=35)),
                ('image', models.ImageField(default='null', null=True, upload_to='project')),
            ],
        ),
    ]
