# Generated by Django 4.2.7 on 2023-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
