# Generated by Django 4.2.5 on 2023-10-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_rename_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
