# Generated by Django 4.2.5 on 2023-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='vaziaate_pasokhgooei',
            field=models.BooleanField(default=False),
        ),
    ]
