# Generated by Django 4.2.5 on 2023-10-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0002_contact_vaziaate_pasokhgooei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='vaziaate_pasokhgooei',
            new_name='وضعیت_پاسخگویی',
        ),
    ]
