# Generated by Django 4.2.6 on 2023-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0003_rename_vaziaate_pasokhgooei_contact_وضعیت_پاسخگویی'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(),
        ),
    ]
